### PR TITLE
Add backticks to identifiers, fixes error with oracle

### LINKED ISSUE #164: Updating AV ruleset fails on both OC9 and 10 (oracle DB)
Hi,

When attempting to update the AV ruleset (Oracle DB backend) error messages are printed to the owncloud log, and no change is committed.

1: Do a change on the ruleset.
2: Press the checkmark buttion and see error in log: image
3: When refreshing page, no change has been committed. 

Tested on both OC 9.1.6 and 10.0.2

OC 10.0.2 error message:
```
{"reqId":"WWXpskpIWoTZzyWmfJRtawAAAAQ","level":3,"time":"2017-07-12T11:19:47+02:00","remoteAddr":"10.248.28.207","user":"Admin","app":"index","method":"POST","url":"/index.php/apps/files_antivirus/settings/rule/save","message":"Exception: {\"Exception\":\"Doctrine\DBAL\Exception\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT * FROM oc_files_avir_status WHERE id = ?' with params [76]:\n\nORA-00942: tabellen eller utsnittet finnes ikke\",\"Code\":0,\"Trace\":\"
#0 /var/www/html/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractOracleDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\OCI8\OCI8Exception))
#1 /var/www/html/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(177): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\OCI8\Driver), Object(Doctrine\DBAL\Driver\OCI8\OCI8Exception), 'SELECT * FROM o...', Array)
#2 /var/www/html/owncloud/lib/private/legacy/db/statementwrapper.php(71): Doctrine\DBAL\Statement->execute()
#3 /var/www/html/owncloud/lib/public/AppFramework/Db/Mapper.php(252): OC_DB_StatementWrapper->execute()
#4 /var/www/html/owncloud/lib/public/AppFramework/Db/Mapper.php(285): OCP\AppFramework\Db\Mapper->execute('SELECT * FROM *...', Array, NULL, NULL)
#5 /var/www/html/owncloud/lib/public/AppFramework/Db/Mapper.php(379): OCP\AppFramework\Db\Mapper->findOneQuery('SELECT * FROM *...', Array, NULL, NULL)
#6 /var/www/html/owncloud/apps/files_antivirus/lib/db/rulemapper.php(37): OCP\AppFramework\Db\Mapper->findEntity('SELECT * FROM *...', Array)
#7 /var/www/html/owncloud/apps/files_antivirus/controller/rulecontroller.php(71): OCA\Files_Antivirus\Db\RuleMapper->find(76)
#8 [internal function]: OCA\Files_Antivirus\Controller\RuleController->save(76, 2, '/.*: OK$/', 'testing', 0)
#9 /var/www/html/owncloud/lib/private/AppFramework/Http/Dispatcher.php(159): call_user_func_array(Array, Array)
#10 /var/www/html/owncloud/lib/private/AppFramework/Http/Dispatcher.php(89): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Files_Antivirus\Controller\RuleController), 'save')
#11 /var/www/html/owncloud/lib/private/AppFramework/App.php(98): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Files_Antivirus\Controller\RuleController), 'save')
#12 /var/www/html/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php(46): OC\AppFramework\App::main('RuleController', 'save', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#13 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#14 /var/www/html/owncloud/lib/private/Route/Router.php(299): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#15 /var/www/html/owncloud/lib/base.php(918): OC\Route\Router->match('/apps/files_ant...')
#16 /var/www/html/owncloud/index.php(49): OC::handleRequest()
#17 {main}\",\"File\":\"/var/www/html/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php\",\"Line\":58}"}
```

OC 9.1.6 error message:
```
{"reqId":"WWXraa3f6dNr3OvSxxICngAAAB4","remoteAddr":"10.248.24.211","app":"index","message":"Exception: {\"Exception\":\"Doctrine\DBAL\Exception\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT * FROM oc_files_avir_status WHERE id = ?' with params [17]:\n\nORA-00942: tabellen eller utsnittet finnes ikke\",\"Code\":0,\"Trace\":\"
#0 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractOracleDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\OCI8\OCI8Exception))
#1 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(175): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\OCI8\Driver), Object(Doctrine\DBAL\Driver\OCI8\OCI8Exception), 'SELECT * FROM o...', Array)
#2 /var/www/html/owncloud/lib/private/legacy/db/statementwrapper.php(75): Doctrine\DBAL\Statement->execute()
#3 /var/www/html/owncloud/lib/public/AppFramework/Db/Mapper.php(251): OC_DB_StatementWrapper->execute()
#4 /var/www/html/owncloud/lib/public/AppFramework/Db/Mapper.php(280): OCP\AppFramework\Db\Mapper->execute('SELECT * FROM *...', Array, NULL, NULL)
#5 /var/www/html/owncloud/lib/public/AppFramework/Db/Mapper.php(372): OCP\AppFramework\Db\Mapper->findOneQuery('SELECT * FROM *...', Array, NULL, NULL)
#6 /var/www/html/owncloud/apps/files_antivirus/lib/db/rulemapper.php(37): OCP\AppFramework\Db\Mapper->findEntity('SELECT * FROM *...', Array)
#7 /var/www/html/owncloud/apps/files_antivirus/controller/rulecontroller.php(71): OCA\Files_Antivirus\Db\RuleMapper->find(17)
#8 [internal function]: OCA\Files_Antivirus\Controller\RuleController->save(17, 2, '/.*: OK$/', 'test', 0)
#9 /var/www/html/owncloud/lib/private/AppFramework/Http/Dispatcher.php(159): call_user_func_array(Array, Array)
#10 /var/www/html/owncloud/lib/private/AppFramework/Http/Dispatcher.php(89): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Files_Antivirus\Controller\RuleController), 'save')
#11 /var/www/html/owncloud/lib/private/AppFramework/App.php(99): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Files_Antivirus\Controller\RuleController), 'save')
#12 /var/www/html/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php(46): OC\AppFramework\App::main('RuleController', 'save', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#13 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#14 /var/www/html/owncloud/lib/private/Route/Router.php(280): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#15 /var/www/html/owncloud/lib/base.php(891): OC\Route\Router->match('/apps/files_ant...')
#16 /var/www/html/owncloud/index.php(54): OC::handleRequest()
#17 {main}\",\"File\":\"/var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php\",\"Line\":58}","level":3,"time":"2017-07-12T11:27:06+02:00","method":"POST","url":"/index.php/apps/files_antivirus/settings/rule/save","user":"emigol"}
```

### PR DESCRIPTION
**Pull request by VicDeo**
Fixes #164

### CODE REVIEW

**Comment by VicDeo** [comment]
@Emil-G Could you please confirm that it works?
It is as easy as changing 1 line in `apps/files_antivirus/lib/db/rulemapper.php`

**Comment by DeepDiver1975** [comment]
Please add oracle to Travis- see activity App.
And Please ensure that all queries are covered by unit tests. 
Issues like that are easy to avoid. 

Thx

**Comment by michaelstingl** [comment]
@VicDeo What is the status here? Any blockers?

**Comment by PVince81** [comment]
@VicDeo please backport to stable10 as the release is still built based on this

**Comment by VicDeo** [comment]
Stable10: #188

**Comment by PVince81** [comment]
@michaelstingl yes, requires the app to actually have an entry in the marketplace, see https://github.com/owncloud/files_antivirus/issues/171

**Pull request merged**
