### PR TITLE
admin.php is a history

### PR DESCRIPTION
**Pull request by VicDeo**
`admin.php` was removed from the repo so the build process is failing.

### CODE REVIEW

**Comment by PVince81** [comment]
@VicDeo please verify if 10.0.1RC3 is affected... From what I see the app is there but I see a Makefile in the folder. So maybe the build worked after all ?

**Comment by VicDeo** [comment]
@PVince81  It seems  makefile from this repo is not used to bundle the app.
RC3 is not affected.
Makefile is sneaked into the release but it's not critical IMO

**Comment by PVince81** [comment]
so does the antivirus app in RC3 work ? (quick smoke test)

**Comment by VicDeo** [comment]
@PVince81 it's possible to enable the app and it detects EICAR on upload

**Comment by PVince81** [comment]
:+1: to merge for 10.0.2 to avoid risks

**Comment by VicDeo** [comment]
Moved to https://github.com/owncloud/files_antivirus/pull/157

**Pull request closed without merging**
