### PR TITLE
coverage

### PR DESCRIPTION
**Pull request by micbar**
# Description

- help #405 with proper coverage

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
sonar-analysis step failed - just retriggered ..... let's see ....

**Comment by micbar** [comment]
checkout path was wrong.

**Comment by DeepDiver1975** [comment]
still no coverage ...

**Comment by micbar** [comment]
it is there https://sonarcloud.io/dashboard?id=owncloud_files_antivirus&pullRequest=406

**Comment by micbar** [comment]
let us merge it, then get coverage in master then check again

**Pull request merged**
