### PR TITLE
[Stable9.1] Optimize DB query. Fetch user_id from DB

### PR DESCRIPTION
**Pull request by VicDeo**
backport of #139 and #159

### CODE REVIEW

**Comment by VicDeo** [comment]
Finally fixed that. :tropical_drink:

**Comment by VicDeo** [comment]
@PVince81 backported as per your comment https://github.com/owncloud/files_antivirus/pull/139#issuecomment-322503441

**Comment by PVince81** [comment]
@VicDeo did you retest and it still works ?

**Comment by VicDeo** [comment]
@PVince81 retested, works. Can't merge due to stupid CLA bot.

**Pull request merged**
