### PR TITLE
Skip zero sized files

### PR DESCRIPTION
**Pull request by VicDeo**
Fixes https://github.com/owncloud/files_antivirus/issues/69

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by fsbruva** [comment]
This does not actually fix the problem. If there are 5 or more zero sized files, the background scanner will continuously select them from the database, but skip them in the while loop.

I will be submitting a pull request shortly that correctly fixes the problem.

**Comment by fsbruva** [comment]
Sorry for the multiple references listed. I had some trouble with my forked repository, and ended up with (obviously) several duplicate commits. The a1a3116 is the correct one, referenced in my pull request.

**Pull request merged**
