### PR TITLE
Use owncloudci/clamavd docker image in CI

### PR DESCRIPTION
**Pull request by phil-davis**
Fixes issue #340

### CODE REVIEW

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/files_antivirus/1381/14/4

clamavd docker image does not actually run `run.sh` - I need to sort out what is needed in the docker image to get that to happen.

**Comment by individual-it** [comment]
image

**Comment by phil-davis** [comment]
The image is not actually running clamav - I need to sort out what I did wrong.

**Review by individual-it — COMMENTED** [review]
what is the status of this PR?

**Comment by phil-davis** [comment]
I was planning to look at it again today.
@individual-it remembering from a month ago, the template structure for owncloud-ci docker is different from what we made in https://github.com/JankariTech/docker-clamavd
So moving this to owncloud-ci is not just a straight copy-paste. I need to work out what needs to be changed in https://github.com/owncloud-ci/clamavd

**Comment by phil-davis** [comment]
`owncloudci/clamav` docker has been updated today. @swoichha is making a new PR to use it...

**Pull request closed without merging**
