### PR TITLE
[tests-only] Test upload of empty file

### PR DESCRIPTION
**Pull request by phil-davis**
Add a test scenario for uploading an empty file, to check issue #438 

We may as well cover this edge case with a test scenario.

### CODE REVIEW

**Comment by VicDeo** [comment]
inter-resting... 
https://github.com/owncloud/files_antivirus/blob/b01b8691a5d5f5ef17bab33daa78b3ee18088c16/lib/Scanner/ICAPScanner.php#L37-L39

**Comment by phil-davis** [comment]
> according to the code it should not ask to scan empty content but bail out with success immediately

which means that there should not be any problem, no matter what ICAP service is being used.

**Comment by VicDeo** [comment]
ok... I need to check. There is  a chance `$this->data === ''` is `false` due to `$this->data`  is null.
strict comparison as is ;)

**Comment by phil-davis** [comment]
> ok... I need to check

It would be nice if a unit test covered that. But it might be tricky because the method will have the same result regardless of which code path is taken.

**Review by individual-it — APPROVED** [review]

**Pull request merged**
