### PR TITLE
[Stable9] fix file not found

### PR DESCRIPTION
**Pull request by VicDeo**
Backport of
#111 #121 #113 #118  to stable9

Needs manual testing

### CODE REVIEW

**Comment by VicDeo** [comment]
@PVince81 @DeepDiver1975 FYI

**Comment by ms270169** [comment]
If you would brief me about correct test setup, I could do that.
Because it's backporting to OC9.0, it should be tested together with OC9.0 system. Right?
I would download latest OC9.0 from release channel (at the moment 9.0.4) and replace app/filese_antivirus with   commit 8eeb2ae292f2ce402a4a86347a78e1de915b1f6f. 
Do you suggest a better way?

**Comment by jvillafanez** [comment]
@ms270169 I'd rather use a stable9 daily package + this patch

The patch is in https://patch-diff.githubusercontent.com/raw/owncloud/files_antivirus/pull/128.patch
Daily stable9 package: https://download.owncloud.org/community/daily/owncloud-daily-stable9.tar.bz2

**Comment by PVince81** [comment]
@owncloud/qa can you help testing this ? Might take some time to setup.

**Comment by SergioBertolinSG** [comment]
👍  Works.

**Comment by PVince81** [comment]
Thanks a lot! Merging.

**Pull request merged**
