### PR TITLE
Fix migration from outdated versions

### PR DESCRIPTION
**Pull request by VicDeo**
Ref https://github.com/owncloud/apps/issues/2075
`oc_files_antivirus_status` was introduced in v0.5 so there is no chance to rename it for all versions prior to this one.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by VicDeo** [comment]
@karlitschek backport?

**Comment by karlitschek** [comment]
yes. please back port :+1:

**Comment by VicDeo** [comment]
Stable8 https://github.com/owncloud/files_antivirus/issues/52

**Pull request merged**
