### PR TITLE
feat: integrate icap scanner as enterprise feature

### PR DESCRIPTION
**Pull request by DeepDiver1975**
# TODO:

- [ ] icap needs to be integrated into the acceptance test suite - maybe something for @individual-it and co
- [x] unit tests for icap
- [ ] define desired behavior when icap is enabled and license expires

### CODE REVIEW

**Comment by micbar** [comment]
>     deesired behavior when icap is enabled and license expires

AFAIK nothing happens, if it is a production license. If it is a demo license, the whole files_antivirus app will be disabled by core.

@hodyroff IMO that needs to be confirmed, but is reasonable IMO

**Comment by DeepDiver1975** [comment]
>  If it is a demo license, the whole files_antivirus app will be disabled by core.

Once the license expires a user could be willing to reconfigure the app to use clamav - which should be possible without a license.
So - no idea if disabling the app is the desired behavior.

@pmaier1 @hodyroff

**Comment by hodyroff** [comment]
As long as disable imap and activate av again means it works again, I am fine with this.

**Comment by DeepDiver1975** [comment]
> As long as disable imap and activate av again means it works again, I am fine with this.

imap -> icap ;-)

Out of the box (meaning without explicit user configuration and installation of clamav) falling back to any other mode will also leave the system in an unusable state (meaning: file uploads will not work)

**Comment by pmaier1** [comment]
> As long as disable imap and activate av again means it works again, I am fine with this.

Yep, in a demo environment this should be fine. We should still make sure that everything continues to work (there were some states with anti-virus being unconfigured where users could not upload files anymore).
In a productive environment we should not disable anything, as said before.

**Comment by VicDeo** [comment]
> there were some states with anti-virus being unconfigured where users could not upload files anymore

which was an explicitly requested and documented... https://github.com/owncloud/core/issues/28870#issuecomment-326413982


>When the app is enabled — but is not configured or has an incorrect configuration — it will reject all uploads for the entire instance. To avoid this situation, make sure the ClamAV service is running and you have the execution mode correctly configured in ownCloud.

Source: https://doc.owncloud.com/server/admin_manual/appliance/configuration/clamav.html

**Comment by DeepDiver1975** [comment]
> Kudos, SonarCloud Quality Gate passed!
> 
> [Bug](https://sonarcloud.io/project/issues?id=owncloud_files_antivirus&pullRequest=405&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=owncloud_files_antivirus&pullRequest=405&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=owncloud_files_antivirus&pullRequest=405&resolved=false&types=BUG)
> [Vulnerability](https://sonarcloud.io/project/issues?id=owncloud_files_antivirus&pullRequest=405&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=owncloud_files_antivirus&pullRequest=405&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=owncloud_files_antivirus&pullRequest=405&resolved=false&types=VULNERABILITY)
> [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=owncloud_files_antivirus&pullRequest=405&resolved=false&types=SECURITY_HOTSPOT) [A](https://sonarcloud.io/project/security_hotspots?id=owncloud_files_antivirus&pullRequest=405&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=owncloud_files_antivirus&pullRequest=405&resolved=false&types=SECURITY_HOTSPOT)
> [Code Smell](https://sonarcloud.io/project/issues?id=owncloud_files_antivirus&pullRequest=405&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=owncloud_files_antivirus&pullRequest=405&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=owncloud_files_antivirus&pullRequest=405&resolved=false&types=CODE_SMELL)
> 
> [No Coverage information](https://sonarcloud.io/component_measures?id=owncloud_files_antivirus&pullRequest=405&metric=coverage&view=list) No Coverage information
> [No Duplication information](https://sonarcloud.io/component_measures?id=owncloud_files_antivirus&pullRequest=405&metric=duplicated_lines_density&view=list) No Duplication information

Why are there no coverage information on PR basis anymore? :confused:

**Comment by micbar** [comment]
> > Kudos, SonarCloud Quality Gate passed!
> > [Bug](https://sonarcloud.io/project/issues?id=owncloud_files_antivirus&pullRequest=405&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=owncloud_files_antivirus&pullRequest=405&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=owncloud_files_antivirus&pullRequest=405&resolved=false&types=BUG)
> > [Vulnerability](https://sonarcloud.io/project/issues?id=owncloud_files_antivirus&pullRequest=405&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=owncloud_files_antivirus&pullRequest=405&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=owncloud_files_antivirus&pullRequest=405&resolved=false&types=VULNERABILITY)
> > [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=owncloud_files_antivirus&pullRequest=405&resolved=false&types=SECURITY_HOTSPOT) [A](https://sonarcloud.io/project/security_hotspots?id=owncloud_files_antivirus&pullRequest=405&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=owncloud_files_antivirus&pullRequest=405&resolved=false&types=SECURITY_HOTSPOT)
> > [Code Smell](https://sonarcloud.io/project/issues?id=owncloud_files_antivirus&pullRequest=405&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=owncloud_files_antivirus&pullRequest=405&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=owncloud_files_antivirus&pullRequest=405&resolved=false&types=CODE_SMELL)
> > [No Coverage information](https://sonarcloud.io/component_measures?id=owncloud_files_antivirus&pullRequest=405&metric=coverage&view=list) No Coverage information
> > [No Duplication information](https://sonarcloud.io/component_measures?id=owncloud_files_antivirus&pullRequest=405&metric=duplicated_lines_density&view=list) No Duplication information
> 
> Why are there no coverage information on PR basis anymore? 😕

That needs a fix in the .drone.star

DroneCI is merging the branch into master before running the CI
Sonarcloud cannot match this to the real branch

To do this, we would need a dedicated `clone` step in the sonarcloud upload pipeline.

**Comment by micbar** [comment]
We just fixed this in ocis, but we need to propagate it to all other repos now.

**Comment by micbar** [comment]
@phil-davis JFYI

**Comment by DeepDiver1975** [comment]
> That needs a fix in the .drone.star
> 
> DroneCI is merging the branch into master before running the CI
> Sonarcloud cannot match this to the real branch
> 
> To do this, we would need a dedicated `clone` step in the sonarcloud upload pipeline.

what a mess ...... anyway - thx for the explanation .... :+1:

**Comment by micbar** [comment]
I can push a fix to this branch

**Comment by DeepDiver1975** [comment]
> I can push a fix to this branch

separate pr + merge + rebase would be cleaner ... right?

**Comment by DeepDiver1975** [comment]
>     * unit tests for icap

```

PHPUnit 8.5.14 by Sebastian Bergmann and contributors.
--

**Comment by micbar** [comment]
@DeepDiver1975 https://github.com/owncloud/files_antivirus/pull/406

**Comment by micbar** [comment]
@DeepDiver1975 SonarScanner is working now.

It reports now the Code Smells. But the coverage is still not showing up.
I need to dig deeper.

Maybe @phil-davis has a hunch. We need to check the sonarcloud settings.

**Pull request merged**
