### PR TITLE
Fix column names in select

### LINKED ISSUE #158: BackgroundScanner-Error: SQLSTATE[42S22]: Column not found (on almost every cron run)
Hi,

since enabling the files_antivirus app and switching from mode "executable" to "Daemon (Socket)" I see the following error on almost every cron run (15 minutes):

```Error	files_antivirus	OCA\Files_Antivirus\BackgroundScanner::run, exception: An exception occurred while executing 'SELECT fc.`fileid, mnt.user_id` FROM `oc_filecache` fc LEFT JOIN `oc_files_antivirus` fa ON fa.`fileid` = fc.`fileid` INNER JOIN `oc_mounts` mnt ON (fc.`storage` = mnt.`storage_id`) AND (mnt.`mount_point` = CONCAT('/', mnt.user_id, '/')) WHERE (fc.`mimetype` <> '2') AND ((fa.`fileid` IS NULL) OR (fc.`mtime` > fa.`check_time`)) AND (fc.`path` LIKE 'files/%') AND (fc.`size` <> '0')': SQLSTATE[42S22]: Column not found: 1054 Unknown column 'fc.fileid, mnt.user_id' in 'field list'	9 minutes ago```

Is there anything missing in the database or is some code looking for something which isn´t there?

I use OC v10.0.2.1 and files_antivirus v0.10.0.0. Clamav-daemon is running locally, files_antivirus connects via socket.

What can I do/check? What further information would help you (to help me) to solve this issue?

### PR DESCRIPTION
**Pull request by VicDeo**
Fixes #158
Needs backport to stable10

### CODE REVIEW

**Comment by VicDeo** [comment]
@DeepDiver1975 done

**Comment by VicDeo** [comment]
@DeepDiver1975 Please revisit this PR

**Comment by PVince81** [comment]
@VicDeo please backport

**Comment by PVince81** [comment]
or might not be needed... just do the market release from master...

**Comment by VicDeo** [comment]
@PVince81 oops. forgot to mention the backport. It's already here.

Stable10: https://github.com/owncloud/files_antivirus/pull/162

**Comment by VicDeo** [comment]
Stable10: https://github.com/owncloud/files_antivirus/pull/174

**Pull request merged**
