### PR TITLE
[tests-only] [full-ci] Bump to phpunit9 in acceptance tests

### PR DESCRIPTION
**Pull request by phil-davis**
`phpunit` was updated to major version 9 in core PR https://github.com/owncloud/core/pull/39290

Also bump to phpunit9 in the acceptance tests.

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIActListICAP-master-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_antivirus/2188/14/1

**Comment by individual-it** [comment]
`Type error: Argument 2 passed to PHPUnit\Framework\Assert::assertNotContains() must be iterable, string given, called in /var/www/owncloud/testrunner/apps/activity/tests/acceptance/features/bootstrap/WebUIActivityContext.php on line 407 (Behat\Testwork\Call\Exception\FatalThrowableError)`

**Comment by phil-davis** [comment]
> `Type error: Argument 2 passed to PHPUnit\Framework\Assert::assertNotContains() must be iterable, string given, called in /var/www/owncloud/testrunner/apps/activity/tests/acceptance/features/bootstrap/WebUIActivityContext.php on line 407 (Behat\Testwork\Call\Exception\FatalThrowableError)`

See https://github.com/owncloud/activity/pull/1009

There are multi-app test scenarios that depend on app code and test code in another app.

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIActList-master-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_antivirus/2189/12/1

**Review by JammingBen — APPROVED** [review]

**Pull request merged**
