### PR TITLE
Fix virus detection for public upload and chunking

### LINKED ISSUE #209: public uploads don't get checked
1. set up the app and make sure it blocks `eicar.com` from http://www.eicar.org/85-0-Download.html
2. create an public link with upload permissions
3. upload `eicar.com`

The problem was introduced by #196

### PR DESCRIPTION
**Pull request by VicDeo**
Fixes #209 #208 
Click links above to see reproduction steps

### CODE REVIEW

**Comment by individual-it** [comment]
works to block uploads that are uploaded with chunking.
But the max size is not obeyed when using old dav chunking

**Comment by PVince81** [comment]
is max size a separate issue ?

**Comment by PVince81** [comment]
@individual-it please raise separate ticket for max size

**Comment by individual-it** [comment]
reopened #179

**Pull request merged**
