### PR TITLE
[Tests-Only][CI] Cancel Old running builds

### PR DESCRIPTION
**Pull request by jasson99**
https://github.com/owncloud/QA/issues/674
- Cancel Old running builds of a PR
**note** this PR was generated by a automated script

Edit: 2021-09-05 added "Update .drone.star and drop PHP 7.2"
Part of issue https://github.com/owncloud/core/issues/39134
and https://github.com/owncloud/QA/issues/687

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiAvScality-master-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_antivirus/2124/29/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiAvScality-latest-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_antivirus/2124/30/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiAvICAP-latest-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_antivirus/2124/28/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiAntivirus-latest-postgres9.4-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_antivirus/2124/25/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiAvCeph-latest-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_antivirus/2124/32/1

**Review by phil-davis — APPROVED** [review]

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIActListICAP-master-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_antivirus/2149/14/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIActList-master-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_antivirus/2149/12/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIActList-master-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_antivirus/2151/12/1

**Pull request merged**
