### PR TITLE
Update appinfo

### PR DESCRIPTION
**Pull request by VicDeo**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@VicDeo please apply labels and milestone on any issue and pr - thx

**Comment by DeepDiver1975** [comment]
please post screenshot of the app management page so that we can see how it looks like - thx

**Comment by VicDeo** [comment]
Here you are
desc

**Comment by DeepDiver1975** [comment]
thx @VicDeo 

@MTRichards fine with you?

**Comment by MTRichards** [comment]
Good stuff! Ok by me.

**Comment by DeepDiver1975** [comment]
@VicDeo please apply these changes to other branches as well - THX

**Comment by VicDeo** [comment]
Stable8 https://github.com/owncloud/files_antivirus/pull/32

**Pull request merged**
