### PR TITLE
Update the env.global.CORE_BRANCH setting in .travis.yml

### PR DESCRIPTION
**Pull request by nickvergessen**

### CODE REVIEW

**Comment by LukasReschke** [comment]
:+1:

**Comment by nickvergessen** [comment]
@VicDeo  tests fail:
```
PHP Fatal error:  Call to undefined method OC_User::createUser() in /home/travis/build/owncloud/core/apps/files_antivirus/tests/itemtest.php on line 30

PHP Stack trace:

PHP   1. {main}() /home/travis/.phpenv/versions/5.4.45/bin/phpunit:0

PHP   2. PHPUnit_TextUI_Command::main() /home/travis/.phpenv/versions/5.4.45/bin/phpunit:545

PHP   3. PHPUnit_TextUI_Command->run() phar:///home/travis/.phpenv/versions/5.4.45/bin/phpunit/phpunit/TextUI/Command.php:100

PHP   4. PHPUnit_TextUI_TestRunner->doRun() phar:///home/travis/.phpenv/versions/5.4.45/bin/phpunit/phpunit/TextUI/Command.php:149

PHP   5. PHPUnit_Framework_TestSuite->run() phar:///home/travis/.phpenv/versions/5.4.45/bin/phpunit/phpunit/TextUI/TestRunner.php:440

PHP   6. PHPUnit_Framework_TestSuite->run() phar:///home/travis/.phpenv/versions/5.4.45/bin/phpunit/phpunit/Framework/TestSuite.php:747

PHP   7. PHPUnit_Framework_TestCase->run() phar:///home/travis/.phpenv/versions/5.4.45/bin/phpunit/phpunit/Framework/TestSuite.php:747

PHP   8. PHPUnit_Framework_TestResult->run() phar:///home/travis/.phpenv/versions/5.4.45/bin/phpunit/phpunit/Framework/TestCase.php:724

PHP   9. PHPUnit_Framework_TestCase->runBare() phar:///home/travis/.phpenv/versions/5.4.45/bin/phpunit/phpunit/Framework/TestResult.php:612

PHP  10. Test_Files_Antivirus_Item->setUp() phar:///home/travis/.phpenv/versions/5.4.45/bin/phpunit/phpunit/Framework/TestCase.php:764
```

please fix

**Comment by nickvergessen** [comment]
Same applies to master then, btw

**Comment by nickvergessen** [comment]
Bump, we are about to release a version with failing tests (although I assume it's only setting up the test and not the functionality)

**Comment by nickvergessen** [comment]
Fixed the test

**Comment by PVince81** [comment]
:+1:

**Comment by VicDeo** [comment]
:+1:

**Comment by PVince81** [comment]
That was stable9... but ok, it's just unit tests

**Pull request merged**
