### PR TITLE
Optimize DB query. Fetch user_id from DB

### LINKED ISSUE #137: BackgroundScanner not scanning on md5'd homes
I saw that the code filters by 'home::%' storages, this will miss the crappy md5 storage entries as per https://github.com/owncloud/core/wiki/Storage-IDs#random-numberstring

The old workaround was to iterate over all users, but it's expensive.

Since OC 9.0 we have the oc_mounts table which is a cache of known mount points, including the user's homes. This should be used to identify the user's home storages.

`select storage_id from oc_mounts where mount_point='/$userId/'`

@VicDeo

### PR DESCRIPTION
**Pull request by VicDeo**
Use oc_mounts instead of oc_storages
Fetch owner's user_id directly from oc_mounts in addition to file_id

Fixes #137
Obsoletes #138

### CODE REVIEW

**Comment by VicDeo** [comment]
@PVince81 please review

**Comment by PVince81** [comment]
Looks good. Is this part covered by CI to confirm that it will pass for all DBs ?

**Comment by VicDeo** [comment]
@PVince81 yes, cronjob is covered by tests

**Comment by PVince81** [comment]
:+1: for the code, not tested. Up to you to get it tested or if you're confident that it's tested enough then merge it.

**Comment by VicDeo** [comment]
@PVince81 what about backporting?

**Comment by PVince81** [comment]
I'd say let's backport to 9.1 only for now.

**Comment by PVince81** [comment]
missing backport

**Comment by VicDeo** [comment]
Stable10: https://github.com/owncloud/files_antivirus/pull/174

**Pull request merged**
