### PR TITLE
[Stable9.1] fix 125

### PR DESCRIPTION
**Pull request by VicDeo**
Backport of #133

### CODE REVIEW

**Comment by PVince81** [comment]
@VicDeo 9.0.7 or 9.0.8 ? How risky is this backport ?

@owncloud/qa what do you think ?

**Comment by VicDeo** [comment]
@PVince81 From my POV not too risky, but let's move to the next release. 
Stable9.1 is the same with master, so it will be easier to make backports in future if we keep both in sync.

**Comment by PVince81** [comment]
@davitol please help testing, thanks

**Comment by davitol** [comment]
:+1: WFM

**Comment by PVince81** [comment]
:+1: for the code

**Pull request merged**
