### PR TITLE
Reject uploads when antivirus is unreachable

### PR DESCRIPTION
**Pull request by VicDeo**
- Reject uploads when antivirus is unreachable/ Fixes https://github.com/owncloud/files_antivirus/issues/181
~Note: it will reject not uploads only but any `fopen` on storage~ - already fixed with #196
-  Adds a connection test after saving the settings. Notify admin  priority label if it is failed. #180 
- Move all scanners into a separate subdir
- Subclass  scan via socket and daemon from parent External
- Cover scanner initialization with unit tests

- [x] TODO:  figure out meaning of `retry` https://github.com/owncloud/core/blob/master/apps/dav/lib/Connector/Sabre/Exception/Forbidden.php#L31
`retry=true` for misconfigured app
`retry=false` for infected files

misconfig-daemon
misconfig-socket
misconfig-executable

### CODE REVIEW

**Comment by VicDeo** [comment]
@ownclouders rebase

**Comment by individual-it** [comment]
works like described, but I would like it more if additionally there would be a check when the configuration  gets saved

**Comment by VicDeo** [comment]
@individual-it this is a different issue (#180) but as you wish ;)

**Comment by VicDeo** [comment]
@individual-it  rereview please

**Pull request merged**
