### PR TITLE
Disable proxies

### PR DESCRIPTION
**Pull request by VicDeo**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Please add clover.xml to gitignore and do not check it in - THX

**Comment by DeepDiver1975** [comment]
> Please add clover.xml to gitignore

Did you miss to add .gitignore ? THX

**Comment by VicDeo** [comment]
@DeepDiver1975 well, I can make it pass now, but the faulty piece is https://github.com/owncloud/core/blob/master/apps/files_encryption/lib/proxy.php#L64

Not every path  has  `$parts[2]`. e.g.  `/foo.txt` hasn't

**Comment by DeepDiver1975** [comment]
@schiesbn can you please have a look - THX

**Comment by schiesbn** [comment]
Maybe we the proxy should check the number of path elements. But can you, @VicDeo, explain to me on what files the antivirus app operates to get a better understanding of the overall problem. The path at the proxy should always start at ```data/```, does the antivirus app operates on files outside of ```data/<user>/files``` ?

**Comment by nickvergessen** [comment]
prepared a patch for it in owncloud/core#13285

**Comment by VicDeo** [comment]
@schiesbn not exact, unit tests use temporary storage that is mounted to the user root directory

**Comment by VicDeo** [comment]
@nickvergessen thanks! :icecream:

**Comment by nickvergessen** [comment]
@VicDeo since my patch got merged, you just need to rebase it here.

**Comment by VicDeo** [comment]
Tests are passing

**Pull request merged**
