### PR TITLE
Send notification to the FS owner

### PR DESCRIPTION
**Pull request by VicDeo**
Fixes https://github.com/owncloud/files_antivirus/issues/12

### CODE REVIEW

**Comment by jerrac** [comment]
Which log level should I test this on?

**Comment by VicDeo** [comment]
@jerrac this should fix sending an email when infected file is uploaded with client.

**Comment by jerrac** [comment]
Ah, sorry. Been concentrating on other things and hadn't quite switched tracks yet... Heh.

So, still no email. Loglevel is "Warnings". I tested it twice.

Here's what I get in syslog. Still no php errors.

```
Jan 23 11:03:56 ws-prod-filehost-01 ownCloud[9345]: {files_antivirus} Virus(es) found: Eicar-Test-SignatureAccount:USERNAME .File:/infected2.exe
Jan 23 11:03:57 ws-prod-filehost-01 ownCloud[9345]: {hook} error while running hook (\OCA\Files_Antivirus\Scanner::av_scan): Session has been closed - no further changes to the session as allowed
Jan 23 11:03:57 ws-prod-filehost-01 ownCloud[9345]: {sharing} No fileinfo available for: /infected2.exe
Jan 23 11:03:57 ws-prod-filehost-01 ownCloud[9345]: {webdav} \OC\Files\Filesystem::rename() failed
Jan 23 11:03:57 ws-prod-filehost-01 ownCloud[9345]: {webdav} Sabre\DAV\Exception: Could not rename part file to final file
```

**Comment by jerrac** [comment]
Erm, it's now blocking all files, not just my test virus file.

{"app":"files_antivirus","message":"Virus(es) found: Account: webmaster File: \/Employee Status Dashboard idea.txt","level":2,"time":"2015-01-26T22:54:36+00:00"}
{"app":"files_antivirus","message":"Virus(es) found: Account: webmaster File: \/epiccat.jpg","level":2,"time":"2015-01-26T22:57:49+00:00"}

Though, it does send emails reporting said false positive even when using the webdav connection.

**Comment by jerrac** [comment]
@VicDeo So, I switched from fix-recipient to master, and master is also blocking all files. So I'm not sure if the code in fix-recipient is really to blame, or if it's something else.

**Comment by VicDeo** [comment]
Rebase has a little sense after the recent changes. Closing.

**Pull request closed without merging**
