### PR TITLE
[Stable8] Fixes #69 by not selecting zero sized files from filecache in the first place.

### LINKED ISSUE #69: "fwrite(): send of 4 bytes failed with errno=32 Broken pipe at \/var\/www\/owncloud\/apps\/files_antivirus\/lib\/scanner.php#68
Hi,

i have a Problem with ownCloud 8.1.0 and files_antivirus 0.7.0.1. I got the following message several times in a second in the owncloud.log:

remoteAddr":"","app":"PHP","message":"fwrite(): send of 4 bytes failed with errno=32 Broken pipe at \/var\/www\/owncloud\/apps\/files_antivirus\/lib\/scanner.php#68","level":3,

I can not find the source of this problem. Is there anyone who knows why this message appears and how i can fix this problem?

### PR DESCRIPTION
**Pull request by VicDeo**
Backport of #83

### CODE REVIEW

**Comment by PVince81** [comment]
@VicDeo please do mention people for review to make sure this gets noticed. Thanks

**Comment by PVince81** [comment]
:+1: makes sense

**Comment by VicDeo** [comment]
@PVince81 I was waiting for the build to complete actually. Do you have permissions to restart Scrutinizer inspection?

**Comment by PVince81** [comment]
@VicDeo I don't have any CI permissions. @DeepDiver1975 has them

**Comment by cmonteroluque** [comment]
@VicDeo can you please test it and reply to @PVince81

**Comment by VicDeo** [comment]
@cmonteroluque I wish it were that fast. Testing right now.

**Comment by VicDeo** [comment]
@cmonteroluque @PVince81 merged

**Comment by cmonteroluque** [comment]
@VicDeo thanks!

**Pull request merged**
