### PR TITLE
Pack buttons into container. Fixes #23

### LINKED ISSUE #23: Minor view bug in advanced tab
in the antivir app admin page, once you clicked on "Advanced" if the screen width is not very wide the buttons "Reset to default" and "Clear All" overlap the text to the left.

### PR DESCRIPTION
**Pull request by VicDeo**
Fixes #23

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@VicDeo can you please add screenshots? Will be easier to review for @MTRichards THX

**Comment by VicDeo** [comment]
Before
before

After
after

**Comment by VicDeo** [comment]
After (even more narrow)
after2

After (table is complete visible)
after-wide

**Comment by DeepDiver1975** [comment]
@MTRichards ui now acceptable? Does it fix the explicit issue you wanted us to target? THX

**Comment by DeepDiver1975** [comment]
@jancborchardt some design might help here as well - THX

**Comment by MTRichards** [comment]
way better! Thank you.

**Comment by DeepDiver1975** [comment]
> way better! Thank you.

thx @MTRichards 

@VicDeo let's merge this and apply the changes to the stables branches (using PRs)

**Comment by jancborchardt** [comment]
Hey, this looks great already! Good job @VicDeo :)

**Comment by VicDeo** [comment]
@DeepDiver1975 Stable8 https://github.com/owncloud/files_antivirus/pull/31

**Pull request merged**
