### PR TITLE
Fix file size check

### LINKED ISSUE #120: Incorrect quoting of file size in anti-virus scanner app
### Steps to reproduce
1. Use Owncloud 9.1
2. Activate and configure files_antivirus app
3. see logfile data/owncloud.log

### Expected behaviour
No error message, working anti-virus scan

### Actual behaviour
The file size 0 bytes is incorrectly quoted in 
```SELECT fc.`fileid` FROM `oc_filecache` fc LEFT JOIN `oc_files_antivirus` fa ON fa.`fileid` = fc.`fileid` INNER JOIN `oc_storages` ss ON (fc.`storage` = ss.`numeric_id`) AND ((ss.`id` LIKE 'local::%') OR (ss.`id` LIKE 'home::%')) WHERE (fc.`mimetype` <> '2') AND ((fa.`fileid` IS NULL) OR (fc.`mtime` > fa.`check_time`)) AND (fc.`path` LIKE 'files\/%') AND (fc.`size` <> `0`) LIMIT 5```

MySQL 5.5.50 reports

`ERROR 1054 (42S22): Unknown column '0' in 'where clause'`

If `0` is manually changed to 0 it works.

The message can be seen in data/owncloud.log:
```
{"reqId":"WEP5biM54YdCUy3m8pEc","remoteAddr":"","app":"files_antivirus","message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception: An exception occurred while executing 'SELECT fc.`fileid` FROM `oc_filecache` fc LEFT JOIN `oc_files_antivirus` fa ON fa.`fileid` = fc.`fileid` INNER JOIN `oc_storages` ss ON (fc.`storage` = ss.`numeric_id`) AND ((ss.`id` LIKE 'local::%') OR (ss.`id` LIKE 'home::%')) WHERE (fc.`mimetype` <> '2') AND ((fa.`fileid` IS NULL) OR (fc.`mtime` > fa.`check_time`)) AND (fc.`path` LIKE 'files\/%') AND (fc.`size` <> `0`) LIMIT 5':\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column '0' in 'where clause'","level":3,"time":"2016-07-25T21:00:06+00:00","method":"--","url":"--","user":"--"}
```

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache 2.4.7

**Database:** MySQL 5.5.50

**PHP version:**

**ownCloud version:** ownCloud 9.1.0 (stable)

**Updated from an older ownCloud or fresh install:** Yes, from 9.0.4

**Where did you install ownCloud from:** Ubuntu packages

**Signing status (ownCloud 9.0 and above):** No, because of one modified authentication app

```
Integrity checker has been disabled. Integrity cannot be verified.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - dav: 0.2.5
  - external: true
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_antivirus: 0.9.0.0
  - files_clipboard: 0.4.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
  - user_external: 0.4
Disabled:
  - encryption
  - files_external
  - user_ldap
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '...',
  'passwordsalt' => '...',
  'secret' => '...',
  'trusted_domains' => 
  array (
    0 => 'www.example.com',
  ),
  'datadirectory' => '/home/owncloud/data',
  'overwrite.cli.url' => 'https://www.example.com/owncloud',
  'dbtype' => 'mysql',
  'version' => '9.1.0.15',
  'dbname' => 'tgmowncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '...',
  'installed' => true,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'mail_smtpmode' => 'sendmail',
  'mail_from_address' => 'root',
  'mail_domain' => 'example.com',
  'ldapIgnoreNamingRules' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'trashbin_retention_obligation' => 'auto',
  'updatechecker' => false,
  'singleuser' => false,
  'htaccess.RewriteBase' => '/owncloud',
);
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** Webdav

### Client configuration
**Browser:** Firefox 47.0

**Operating system:** Linux

#### ownCloud log (data/owncloud.log)
```
{"reqId":"WEP5biM54YdCUy3m8pEc","remoteAddr":"","app":"files_antivirus","message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception: An exception occurred while executing 'SELECT fc.`fileid` FROM `oc_filecache` fc LEFT JOIN `oc_files_antivirus` fa ON fa.`fileid` = fc.`fileid` INNER JOIN `oc_storages` ss ON (fc.`storage` = ss.`numeric_id`) AND ((ss.`id` LIKE 'local::%') OR (ss.`id` LIKE 'home::%')) WHERE (fc.`mimetype` <> '2') AND ((fa.`fileid` IS NULL) OR (fc.`mtime` > fa.`check_time`)) AND (fc.`path` LIKE 'files\/%') AND (fc.`size` <> `0`) LIMIT 5':\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column '0' in 'where clause'","level":3,"time":"2016-07-25T21:00:06+00:00","method":"--","url":"--","user":"--"}
```

### PR DESCRIPTION
**Pull request by fcturner**
Fixes #120

### CODE REVIEW

**Comment by fcturner** [comment]
Now outputs `OCAFiles_AntivirusBackgroundScanner::run, exception: Only strings, Literals and Parameters are allowed` in log...

**Comment by fcturner** [comment]
Fixed!!! Works for me, and the solution is obvious.

**Comment by VicDeo** [comment]
@fcturner Many thanks :+1:

**Comment by VicDeo** [comment]
@DeepDiver1975 @dragotin
9.1 is affected. Backport?

**Comment by dragotin** [comment]
@VicDeo I'd say so, yes, thanks!

**Comment by VicDeo** [comment]
Stable9.1: https://github.com/owncloud/files_antivirus/pull/123

**Pull request merged**
