### PR TITLE
Frontend Validation

### PR DESCRIPTION
**Pull request by VicDeo**
Ref #178 : 
>the fields 'Host', 'Port', 'Stream Length' & 'File size limit' should be validated better.
All fields seem to accept any character. At least "Port" and "File size limit" do not save strings that do not look like integer, the other fields do.
But you can enter a "minus" in the port field. e.g. "Port : -3310" and it get saved
In 'Host' and 'Stream Length' its possible to enter any kind of rubbish and it gets saved.

### CODE REVIEW

**Comment by VicDeo** [comment]
Regarding hostname: it could be either IP address or domain name including IDNA :\

**Comment by individual-it** [comment]
Error messages show two dots at the end of the sentence
image

**Comment by individual-it** [comment]
otherwise it looks good 👍 
also seems to fix #183

**Comment by VicDeo** [comment]
@individual-it a-ha. it is firefox thing. No extra dot in chrome

**Comment by VicDeo** [comment]
@individual-it  updated

Please note that only master is wired to get translations from Transifex.
If we remove this dot from the messages  for stable branches all translations will be lost.

**Comment by VicDeo** [comment]
... aand one more commit (above) fixing the following issue:

1. Delete port value for daemon mode  
```
php occ config:delete files_antivirus av_port
```
2. try to save settings in Executable mode

expected: settings are saved
actual: invisible port input doesn't pass validation

**Comment by VicDeo** [comment]
@individual-it Somehow I've managed to reproduce #183 by playing with different modes in settings.
The fix is also pushed here.

**Comment by VicDeo** [comment]
@PVince81 backport?

**Comment by PVince81** [comment]
@VicDeo yes

**Comment by VicDeo** [comment]
Stable10: https://github.com/owncloud/files_antivirus/pull/189

**Pull request merged**
