### PR TITLE
Move executable options into config.php

### PR DESCRIPTION
**Pull request by VicDeo**
## Documentation relevant
new `config.sample.php` options are
`files_antivitus.av_path`
`files_antivitus.av_cmd_options`

- [x] dependant core PR  https://github.com/owncloud/core/pull/38753

### CODE REVIEW

**Comment by mmattel** [comment]
docs relevant, pls file a docs issue when close to merging
@EParzefall fyi

**Comment by VicDeo** [comment]
@C0rby it's passing now but I think we should have a linked PR in core that updates `config.sample.php` accordingly

**Comment by mmattel** [comment]
> @C0rby it's passing now but I think we should have a linked PR in core that updates `config.sample.php` accordingly

Yes pls make one and add me as reviewer to take care things are written in the way how the docs process needs it.

**Review by jnweiger — APPROVED** [review]
LGTM

thanks!

**Pull request merged**
