### PR TITLE
Use new settings registration method in info.xml

### PR DESCRIPTION
**Pull request by tomneedham**

### CODE REVIEW

**Comment by VicDeo** [comment]
mmm. Incompatible PHPUnit version?
```
PHP Fatal error:  Call to undefined method PHPUnit_Util_Configuration::getTestdoxGroupConfiguration() in /home/travis/build/owncloud/core/lib/composer/phpunit/phpunit/src/TextUI/TestRunner.php on line 1076
PHP Stack trace:
PHP   1. {main}() /home/travis/.phpenv/versions/5.6.5/bin/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /home/travis/.phpenv/versions/5.6.5/bin/phpunit:722
PHP   3. PHPUnit_TextUI_Command->run() phar:///home/travis/.phpenv/versions/5.6.5/bin/phpunit/phpunit/TextUI/Command.php:104
PHP   4. PHPUnit_TextUI_TestRunner->doRun() phar:///home/travis/.phpenv/versions/5.6.5/bin/phpunit/phpunit/TextUI/Command.php:152
PHP   5. PHPUnit_TextUI_TestRunner->handleConfiguration() /home/travis/build/owncloud/core/lib/composer/phpunit/phpunit/src/TextUI/TestRunner.php:167
```

**Comment by DeepDiver1975** [comment]
Yes.  Travis uses different phpunit version for different php versions

**Comment by tomneedham** [comment]
@VicDeo got travis using composers phpunit from core, can you take a look at the errors it pops up now?

**Comment by VicDeo** [comment]
argh. Old cheat to skip trashbin doesn't work anymore :(

**Comment by VicDeo** [comment]
@tomneedham please rename lib/AdminPanel.php to lowercase.
According to my tests it doesn't appear in the settings section otherwise:
```
{"reqId":"pqfjWQ21r9BLPuhG9DuZ","remoteAddr":"127.0.0.1","app":"no app in context","message":"Failed to load panel: OCA\\Files_Antivirus\\AdminPanel with error: Could not resolve OCA\\Files_Antivirus\\AdminPanel! Class OCA\\Files_Antivirus\\AdminPanel does not exist","level":3,"time":"2017-03-13T22:40:46+00:00","method":"GET","url":"\/~deo\/oc-tmp\/index.php\/settings\/admin?sectionid=storage","user":"D"}

```
I think switching to CamelCase is out of scope here.

**Comment by DeepDiver1975** [comment]
> I think switching to CamelCase is out of scope here.

yes - at least in this pr

**Comment by DeepDiver1975** [comment]
thx @VicDeo

**Pull request merged**
